# -*- coding: utf-8 -*-
"""Day-2 FDP_DAV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKE4mI4aa0XrS2hzyMt5lR2MN5ZETa0k
"""

# Import libraries
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Generate x values
x = np.linspace(-5, 5, 100)

# Generate normal distribution values
y = norm.pdf(x, 0, 1)

# Plot bell-shaped curve
plt.plot(x, y)

# Add title and labels
plt.title("Bell-Shaped Curve (Normal Distribution)")
plt.xlabel("X Values")
plt.ylabel("Probability Density")

# Display graph
plt.show()

Brain_Cancer_Prediction

!pip install pandas matplotlib scikit-learn

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load dataset

df=pd.read_csv("brain_cancer_data.csv")

# Display dataset

print("Dataset Loaded Successfully")
print(df)

# Input features

X = df[["Age", "Headache", "MRI_Score", "Tumor_Size"]]

# Output label

y = df["Cancer"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression()

model.fit(X_train, y_train)

print("Model Trained Successfully")

predictions = model.predict(X_test)

print("Predictions:")
print(predictions)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

new_patient = [[42, 5, 80, 4]]

result = model.predict(new_patient)

if result[0] == 1:
    print("⚠ Brain Cancer Detected")
else:
    print("✅ Normal Condition")

df["Cancer"].value_counts().plot(kind="bar")

plt.title("Cancer vs Normal Patients")
plt.xlabel("Condition")
plt.ylabel("Count")

plt.show()